export const BSL_VIDEO_MAP = {
  hello: require("../../assets/bsl/hello.mp4"),
  thank_you: require("../../assets/bsl/thank_you.mp4"),
  cough_medicine: require("../../assets/bsl/cough_medicine.mp4"),
  how_old: require("../../assets/bsl/how_old.mp4"),
  allergy: require("../../assets/bsl/allergy.mp4"),
  amazing: require("../../assets/bsl/amazing.mp4"),
  appointment: require("../../assets/bsl/appointment.mp4"),
  deaf: require("../../assets/bsl/deaf.mp4"),
  exam: require("../../assets/bsl/exam.mp4"),
  good_morning: require("../../assets/bsl/good_morning.mp4"),
  how_are_you: require("../../assets/bsl/how_are_you.mp4"),
  I_am_deaf: require("../../assets/bsl/I_am_deaf.mp4"),
  mask: require("../../assets/bsl/mask.mp4"),
  monday: require("../../assets/bsl/Monday.mp4"),
  sick: require("../../assets/bsl/sick.mp4"),
  sign: require("../../assets/bsl/sign.mp4"),
  tomorrow: require("../../assets/bsl/tomorrow.mp4"),
  when: require("../../assets/bsl/when.mp4"),
  where_does_it_hurt: require("../../assets/bsl/where_does_it_hurt.mp4"),
  where: require("../../assets/bsl/where.mp4"),
  yesterday: require("../../assets/bsl/yesterday.mp4"),
};